<?php

$skip_emails = [
    '@course-fitness.com',
    '2.83.51.s.b.9.xm@dynainbox.com',
    'alspeersxmz7@outlook.com',
    'info@needvirtualassistant.com',
    'outreach@morelocalclients.net',
    'no-replywheva@gmail.com',
    'donayb7@sora5710.kaede39.officemail.in.net',
    'donelleej13ter@outlook.com',
    'frideamrik2@hotmail.com',
    'friend@tour-med.com',
    'c.h.a.r.med.c.rist.k.t.@gmail.com',
    'g.allan.ta.tta.ck.er.@gmail.com',
    'g.al.la.n.ta.t.tac.k.e.r@gmail.com',
    'gallant.a.tt.ac.k.e.r@gmail.com',
    'griskafishka234@gmail.com',
    'hunterlmx6347@gmail.com',
    'hvqsjdib@gmail.com',
    'julianamk18@hikaru3910.hiraku97.officemail.in.net',
    'kai.rus.sell009.8@gmail.com',
    'kai.russell009.8@gmail.com',
    'kostanboloyan@gmail.com',
    'lidam3regrundy@outlook.com',
    'pozvonochnik.od.ua@gmail.com',
    'seller.amazon.web@gmail.com',
    's.c.ot.tr.o.b.bi.nsd.brm.5u.@gmail.com',
    'sc.ottro.b.b.ins.dbrm5.u.@gmail.com',
    'timofeeffsergey83@gmail.com',
    'webmaster@gameplayin.net',
    'zelatcol@gmail.com',
];

$skip_phrases = [
    'porn',
    'galleries',
    'teens',
    'pussy',
    'sexy',
    'sex',
    'lose weight',
    'attention',
    'child',
    'robot',
    'make money',
    'increase your financial',
    'earn additional money',
    'erection',
    'fuck',
    'playmate',
    'nude',
    'naked',
    'need cash',
    'need money',
];
